apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: account-service
spec:
  type: NodePort
  selector:
    app: account-service
  ports:
    - protocol: "TCP"
      port: 8016 # The port that the service is running on in the cluster
      targetPort: 8016 # The port exposed by the service
  type: NodePort # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: account-service
spec:
  selector:
    matchLabels:
      app: account-service
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service 
          image: lsetproject2024/account-service:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8016 # The port that the container is running on in the cluster
          env:      
            - name: CLINTRA_ENCRYPTION_KEY
              valueFrom:
                configMapKeyRef:
                  name: clintra-secrete-config
                  key: CLINTRA_ENCRYPTION_KEY
      imagePullSecrets:
        - name: clintracred
